language: php

# directories to cache
cache:
    directories:
        - vendor
        - $HOME/.composer/cache

php:
    - '7.0'
    - '7.1'
    - '7.2'
    - '7.3'

# test only master (+ pull requests)
branches:
    only:
        - master

# make sure to update composer to latest available version
before_install:
    - phpenv config-add travis.php.ini

# install dependencies
install:
    - travis_wait composer install

# execute phpunit as the script command
script:
    - composer test

# disable mail notifications
notification:
    email: false

# reduce depth (history) of git checkout
git:
    depth: 30

# we don't need sudo
sudo: false
