services:
    prime.translations.menu_plugin:
        class: Prime\Bundle\TranslationsBundle\MenuPlugin\TranslationsMenuPlugin
        public: false
        arguments:
            - "%kernel.bundles%"
        tags:
            - { name: "netgen_admin_ui.menu_plugin", priority: -20 }
